version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: app            
      MYSQL_PASSWORD: apppass    
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"           # opcional: expón solo si lo necesitas

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: apppass
      DB_NAME: ${MYSQL_DATABASE}
      PORT: 5000
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      - ./backend:/app        # permite hot-reload con nodemon
    ports:
      - "5000:5000"

volumes:
  db_data:
